[project]
name = "complianceqa-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tanvi1008665", email = "tgarg1107@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
complianceqa-pipeline = "complianceqa_pipeline:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
